### ISSUE TITLE
different from your article

### ISSUE THREAD

**Issue by toklok** [kmelve/sanity-chatbot-simple-demo#1]
the schema in this repo is different from your article, is this just from experience and your findings?  i'm trying to understand how I can connect it all together.  

https://hackernoon.com/put-your-chatbot-where-your-headless-cms-is-15cf174774c6

**Comment by kmelve** [comment]
This repo is really just an example that I made based on a conversation I had with a developer in our community. The article was written before I started at Sanity, and isn't really connected with this :) If you're interested in exploring this more I'd recommend you to join our [slack](https://slack.sanity.io].
